apiVersion: v1

kind: Service

metadata:
  name: appointment-service-clusterip-service

spec:
  type: ClusterIP

  ports:
    - port: 80
      targetPort: 4000

  selector:
      server: appointmentservice

